### ISSUE TITLE
Free Camera doesn't work with an application

### ISSUE THREAD

**Issue by Xcalibur10** [dtrebilco/glintercept#1]
Hi!

Well, maybe not the best place to write it, because I'm not sure if it's a bug or issue at all with GLIntercept. I tried to use it on PPSSPP emulator with OpenGL backend. It looks like it works, since I can log, I can enable wireframe mode. So some functions are working. But I can't move the camera at all with the predefined config file. I tested it in an other OpenGL application, and it was working.

And I have no idea, if it's possible to fix it by some GLIntercept or PPSSPP settings. I wonder if there is any solution for this. I would like to learn something about a game. If it's not possible to make it work, why? What's the technical issue with it?

**Comment by dtrebilco** [comment]
Hi,
The free camera plugin only works if the application uses the old fixed function setup of the modelview matrices.

At a quick glance at the source it seems it uses shaders when in OpenGL mode - so the free camera stuff will not works unless they use the older interface when supplying the matrices to the shader.

Basically flythrought only really works with OpenGL 1.x. (unless thye use the old interface with shaders)

Thanks.
Damian

**Comment by Xcalibur10** [comment]
Thanks for the explanation, Damian!
