### ISSUE TITLE
How are release packages generated?

### ISSUE THREAD

**Issue by DziubanMaciej** [dtrebilco/glintercept#17]
Is there a script to generate manual install packages and/or installers like in [releases](https://github.com/dtrebilco/glintercept/releases/tag/1.3.4)? How are these packages created? I'm adding some new settings in gliConfig.ini and it would be nice if I could regenerate all the  [example profiles](https://github.com/dtrebilco/glintercept/tree/master/Bin/Profiles) to contain them.

**Comment by dtrebilco** [comment]
The installers scripts are in https://github.com/dtrebilco/glintercept/tree/master/3rdParty/Install 
It uses a program called Inno Setup https://jrsoftware.org/isinfo.php
