### ISSUE TITLE
Flagging an image as dirty when it is not ready/init?

### ISSUE THREAD

**Issue by computerquip** [dtrebilco/glintercept#3]
I'm not sure what this message means. It get's spammed a million times in my log... I'm guessing anytime I'm doing texturing. Could I have a brief explanation?

**Comment by dtrebilco** [comment]
Hi,
This is coming from the image logger (Which you can turn off if you are not
using it).

A verbose description of the error would be "There is an image/texture that
is now being marked as dirty - as there is new data being set in it - but
as far as I can tell, there was no original data set on the image."

Eg This could happen if you called glTexSubImage2D without first calling
glTexImage2D.

Also, the image logger was written in OpenGL 2.0 days - so if you are
creating images with more modern methods - the logger gets confused.

Thanks,
Damian Trebilco

**Comment by computerquip** [comment]
Thanks, seems this is caused when using glTextureStorage.
