### ISSUE TITLE
ShaderGLSLManager not supporting all shadertypes?

### ISSUE THREAD

**Issue by pixeljetstream** [dtrebilco/glintercept#5]
Currently: VS,FS,GS
tessellation and compute are missing.

**Comment by dtrebilco** [comment]
Those were not available at the time the system was written.
Is this something you need? - that a more modern debugger like renderdoc
does not provide?

On Tue, Jul 5, 2016 at 10:41 PM, Christoph Kubisch <notifications@github.com

**Comment by pixeljetstream** [comment]
for sake of completeness it would be very nice to have. glintercept works great as basic tool to get an idea what's going on in an application. Many other trace tools while more concept, also tend to stumble more when they don't support certain things. Or focus too much on capturing all data for replay.

**Comment by dtrebilco** [comment]
I am working on adding basic support - expect it in a few days. I can only do limited testing.

**Comment by dtrebilco** [comment]
1.3.4 adds basic support - still no support for separate shader stages if you use them however.

**Comment by pixeljetstream** [comment]
thanks
