### ISSUE TITLE
Error in gliLog

### ISSUE THREAD

**Issue by aj2work** [dtrebilco/glintercept#6]
I have a plugin for GL Interceptor installed for Neptunia Re;Birth 3.  After installing the full GL Interceptor folder and creating a config.ini file, the log is now saying:

ConfigParser::ExtractTokens - Un-expected '{' 

What does this mean?  Is there a step I can take to remove this error?

**Comment by dtrebilco** [comment]
It seems you have an extra brace in the gliconfig.ini file. Can you try using one of the prebuilt ones or positing it here?
